### ISSUE TITLE
bug - pending recreate - socket hang up error when responding to questions

### ISSUE THREAD

**Issue by Shaulbm** [Claro-Mentor/moovNowMVP#328]
Verify this still happens in Uvicorn 0.18.2

[DEBUG] [07-08-2022 11:24:21.2121]      [MOOV] calling http://xxx.xxx.xxx.xxx:8000/journeySetQuestionResponse?&questionId=Q005&responseId=R017
[ERROR] [07-08-2022 11:24:21.2121]      [MOOV] Error occured when fetching journeySetQuestionResponse: socket hang up
[ERROR] [07-08-2022 11:24:21.2121]      [MOOV] error middleware
[ERROR] [07-08-2022 11:24:21.2121]      [MOOV] Error: socket hang up
    at connResetException (internal/errors.js:639:14)
    at Socket.socketOnEnd (_http_client.js:499:23)
    at Socket.emit (events.js:412:35)
    at Socket.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[INFO] [07-08-2022 11:24:21.2121]       [MOOV] Other Error
[INFO] [07-08-2022 11:24:21.2121]       [MOOV] [RES] [200 undefined] for GET /api/discovery-process/journeySetQuestionResponse?questionId=Q005&responseId=R017
[DEBUG] [07-08-2022 11:24:21.2121]      [MOOV] [RES] Duration: NaN, Response body: {"message":"General Error","name":"GeneralError","errorCode":"500-9000","data":"socket hang up"}

**Comment by Shaulbm** [comment]
did not recreate after uvicorn update
