### ISSUE TITLE
Exception when responding to WA msg

### ISSUE THREAD

**Issue by Shaulbm** [Claro-Mentor/moovNowMVP#680]
[2024-07-07T09:02:59.788] - uvicorn.access - INFO: 172.31.20.216:63168 - "POST /incommingWhatsappMsg HTTP/1.1" 500
[2024-07-07T09:02:59.789] - uvicorn.error - ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\middleware\base.py", line 41, in call_next
    message = await recv_stream.receive()
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\anyio\streams\memory.py", line 81, in receive
    return self.receive_nowait()
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\anyio\streams\memory.py", line 74, in receive_nowait
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\fastapi\applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\middleware\base.py", line 63, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\dev\lighthouseBE\lightouseBE\lbe\src\main.py", line 50, in get_user_details_from_header
    response = await call_next(request)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\middleware\base.py", line 44, in call_next
    raise app_exc
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\middleware\base.py", line 34, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\dev\lighthouseBE\lightouseBE\lbe\src\gateway.py", line 1043, in incomming_whatsapp_msg
    return moovIntermediate.handleIncommingWAMsg(body=requestBody)
  File "C:\dev\lighthouseBE\lightouseBE\lbe\src\moovIntermediate.py", line 140, in handleIncommingWAMsg
    self.logic.setUserResponseToDriverGap(userDetails=userDetails,questionId=lastQuestion.questionId, score=score)
  File "C:\dev\lighthouseBE\lightouseBE\lbe\src\moovLogic.py", line 1886, in setUserResponseToDriverGap
    userGapAggregatedData.aggregatedData.append(newGapEntry)
AttributeError: 'NoneType' object has no attribute 'aggregatedData'

another one:
[2024-07-28T09:20:24.983] - uvicorn.error - ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\middleware\base.py", line 41, in call_next
    message = await recv_stream.receive()
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\anyio\streams\memory.py", line 81, in receive
    return self.receive_nowait()
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\anyio\streams\memory.py", line 74, in receive_nowait
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\fastapi\applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\middleware\base.py", line 63, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\dev\lighthouseBE\lightouseBE\lbe\src\main.py", line 50, in get_user_details_from_header
    response = await call_next(request)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\middleware\base.py", line 44, in call_next
    raise app_exc
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\middleware\base.py", line 34, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "C:\dev\lighthouseBE\lightouseBE\moov.venv\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\dev\lighthouseBE\lightouseBE\lbe\src\gateway.py", line 1053, in incomming_whatsapp_msg
    return moovIntermediate.handleIncommingWAMsg(body=requestBody)
  File "C:\dev\lighthouseBE\lightouseBE\lbe\src\moovIntermediate.py", line 140, in handleIncommingWAMsg
    self.logic.setUserResponseToDriverGap(userDetails=userDetails,questionId=lastQuestion.questionId, score=score)
  File "C:\dev\lighthouseBE\lightouseBE\lbe\src\moovLogic.py", line 1920, in setUserResponseToDriverGap
    userGapAggregatedData.aggregatedData.append(newGapEntry)
AttributeError: 'NoneType' object has no attribute 'aggregatedData'

**Comment by Shaulbm** [comment]
solved when handling when userGapAggregatedData is None:
