### ISSUE TITLE
opening a team member and failing to see his motivations

### ISSUE THREAD

**Issue by Shaulbm** [Claro-Mentor/moovNowMVP#683]
https://claro.one/api/motivations/motivationsForUser?userId=d99390b1-903f-4ea3-8f0c-da2eab7afdee

[INFO] [15-07-2024 07:21:52.5252]       [MOOV] calling http://X.X.X.X:8000/verifyFeature?featureId=emergancy_moovs_for_team_6db239914228
[INFO] [15-07-2024 07:21:52.5252]       [MOOV] calling http://X.X.X.X:8000/verifyFeature?featureId=driver_moovs_for_team_def4f45a66a5
in endMOov.Express
calling http://X.X.X.X:8000/getTopRecommendedMoovs?counterpartId=d99390b1-903f-4ea3-8f0c-da2eab7afdee
[INFO] [15-07-2024 07:21:57.5757]       [MOOV] get user data by id
calling http://X.X.X.X:8000/userScore?counterpartId=d99390b1-903f-4ea3-8f0c-da2eab7afdee
calling http://X.X.X.X:8000/userMotivations?userId=d99390b1-903f-4ea3-8f0c-da2eab7afdee
calling http://X.X.X.X:8000/alertsForCounterpart?counterpartId=d99390b1-903f-4ea3-8f0c-da2eab7afdee
[ERROR] [15-07-2024 07:21:57.5757]      [MOOV] Error occured when fetching userMotivaitons: Error: read ECONNRESET
[ERROR] [15-07-2024 07:21:57.5757]      [MOOV] error middleware
[ERROR] [15-07-2024 07:21:57.5757]      [MOOV] Error: Error occured when fetching userMotivaitons: Error: read ECONNRESET
    at Function.<anonymous> (C:\Claro\moov_server\src\services\motivations\motivations.service.ts:32:19)
    at Generator.throw (<anonymous>)
    at rejected (C:\Claro\moov_server\src\services\motivations\motivations.service.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[INFO] [15-07-2024 07:21:57.5757]       [MOOV] Other Error
[INFO] [15-07-2024 07:21:57.5757]       [MOOV] [RES] [200 undefined] for GET /api/motivations/motivationsForUser?userId=d99390b1-903f-4ea3-8f0c-da2eab7afdee
[INFO] [15-07-2024 07:21:57.5757]       [MOOV] calling http://X.X.X.X:8000/verifyFeature?featureId=driver_moovs_for_team_def4f45a66a5
calling http://X.X.X.X:8000/pastMoovsForCounterpart?counterpartId=d99390b1-903f-4ea3-8f0c-da2eab7afdee
calling http://X.X.X.X:8000/activeMoovsForCounterpart?counterpartId=d99390b1-903f-4ea3-8f0c-da2eab7afdee
[INFO] [15-07-2024 07:21:57.5757]       [MOOV] calling http://X.X.X.X:8000/verifyFeature?featureId=emergancy_moovs_for_team_6db239914228
[INFO] [15-07-2024 07:21:57.5757]       [MOOV] calling http://X.X.X.X:8000/verifyFeature?featureId=engagement_moovs_for_team_6f24e83bba62

**Comment by Shaulbm** [comment]
does not recreate - not enough sdata
